@startuml
'https://plantuml.com/sequence-diagram

!include Style.puml

hide footbox

participant ":PlannerCommand" as plc COMMANDS_COLOR
participant ":PlannerPromptHandler" as prompt PLANNER_COLOR
participant ":Planner" as planner PLANNER_COLOR
participant ":PlannerStorage" as pls PLANNER_COLOR

group sd handleConflict

planner -> planner : hasTimeConflict(event)
activate planner

planner --> planner : hasConflict
deactivate planner

opt hasTimeConflict && !allowConflict

planner --> plc : exception

create prompt
plc -> prompt : create with planner and message
activate prompt

prompt --> plc
deactivate prompt

plc -> prompt : handleEventConflict(event)
activate prompt

loop reply is not "yes" or "no"

prompt -> prompt : getReplyFromPrompt()
activate prompt

prompt --> prompt : reply
deactivate prompt

alt reply is "yes"

prompt -> planner : addEvent(event, true)
activate planner

planner -> pls : writeFile(event.toData())
activate pls

pls --> planner
deactivate pls

planner --> prompt
deactivate planner

prompt --> plc

else reply is "no"

prompt --> plc : exception

else else

prompt -> prompt : changeMessage(INVALID_REPLY_ERROR)
activate prompt

prompt --> prompt
deactivate prompt

end

end

deactivate prompt
destroy prompt

end

end

@enduml