@startuml
'https://plantuml.com/sequence-diagram

!include Style.puml

hide footbox

participant ":Parser" as parser UTIL_COLOR
participant ":TimetableCommand" as command COMMANDS_COLOR
participant ":Timetable" as table TIMETABLE_COLOR
participant ":CommandResult" as result COMMANDS_COLOR

[-> parser : parse input

activate parser

parser -> parser : get subCommand
activate parser

create command
parser -> command : create with lessonDetails

activate command

command --> parser : command

deactivate command

parser --> parser : command
deactivate parser

parser -->[ : command
deactivate parser


[-> command : executeCommand()
activate command


command -> command : addLesson()
activate command
create table
command -> table : new Timetable(moduleList)
activate table
table--> command
deactivate table

ref over command, table : Timetable add operation


create result
command -> result : new CommandResult(ADD_LESSON_MESSAGE)
activate result

result --> command : result
deactivate result
command --> command : result
deactivate command

command -->[ : result
deactivate command




@enduml