@startuml
'https://plantuml.com/sequence-diagram

!include Style.puml

hide footbox
participant ":Parser" UTIL_COLOR
participant ":BusRouteCommand" COMMANDS_COLOR
participant ":Location" ROUTES_COLOR
participant ":DirectRoute" ROUTES_COLOR
participant ":IndirectRoute" ROUTES_COLOR
-> ":Parser": parse input
activate ":Parser"
create ":BusRouteCommand"
":Parser" -> ":BusRouteCommand" : create with input
activate ":BusRouteCommand"
return command
deactivate ":BusRouteCommand"
<-- ":Parser": command
deactivate ":Parser"
-> ":BusRouteCommand": executeCommand()
activate ":BusRouteCommand"
alt command == bus stop list
create ":Location"
":BusRouteCommand" -> ":Location"
activate ":Location"
return
deactivate ":Location"
":BusRouteCommand" -> ":Location": getBusStopList()
activate ":Location"
":Location" --> ":BusRouteCommand": List of all stops
deactivate ":Location"
else else
":BusRouteCommand" -> ":BusRouteCommand": getBusRoutes()
activate ":BusRouteCommand"
create ":DirectRoute"
":BusRouteCommand" -> ":DirectRoute": checkDirectRoute()
activate ":DirectRoute"
":DirectRoute" -> ":DirectRoute": getBusStopNames()
activate ":DirectRoute"
deactivate ":DirectRoute"
":DirectRoute" --> ":BusRouteCommand"
deactivate ":DirectRoute"
create ":IndirectRoute"
":BusRouteCommand" -> ":IndirectRoute"
activate ":IndirectRoute"
":IndirectRoute" -> ":IndirectRoute": getBusStopNames()
activate ":IndirectRoute"
deactivate ":IndirectRoute"
":IndirectRoute" --> ":BusRouteCommand":
deactivate ":IndirectRoute"
alt direct route
":BusRouteCommand" -> ":DirectRoute": checkDirectRoute()
activate ":DirectRoute"
":DirectRoute" --> ":BusRouteCommand"
deactivate ":DirectRoute"
else indirect Route
":BusRouteCommand" -> ":IndirectRoute": checkIndirectRoute()
activate ":IndirectRoute"
":IndirectRoute" --> ":BusRouteCommand"
deactivate ":IndirectRoute"
else else
":BusRouteCommand" -> ":DirectRoute": checkAlternateRoute()
activate ":DirectRoute"
":DirectRoute" --> ":BusRouteCommand"
deactivate ":DirectRoute"
end
":BusRouteCommand" --> ":BusRouteCommand": message
deactivate ":BusRouteCommand"
end
<-- ":BusRouteCommand": result
deactivate ":BusRouteCommand"
@enduml