@startuml
'https://plantuml.com/sequence-diagram

!include Style.puml

hide footbox

participant ":CapCalculatorByCode" as calculator CAPCALCULATOR_COLOR
participant "modules:CalculatorModuleList" as modules MODULE_COLOR
participant "invalidModules:ArrayList" as invalidModules MODULE_COLOR
participant ":ModuleDb" as moduleDb MODULE_COLOR

group sd createCalculator

create modules
calculator -> modules : new CalculatorModuleList()
activate modules

modules --> calculator
deactivate modules

create invalidModules
calculator -> invalidModules : new ArrayList<>()
activate invalidModules

invalidModules --> calculator
deactivate invalidModules

create moduleDb
calculator -> moduleDb : new ModuleDb()
activate moduleDb

moduleDb --> calculator : moduleDb
deactivate moduleDb

calculator -> moduleDb : getPreInitModuleDb()
activate moduleDb

moduleDb --> calculator
deactivate moduleDb

calculator -> calculator : getInputModules(input)
activate calculator

loop for all input modules

alt contains invalid format/invalid code/invalid grade

calculator -> invalidModules : add(commandDescriptions[i + 2])
activate invalidModules

invalidModules --> calculator
deactivate invalidModules

else else
calculator -> modules : storeModuleCodeGrade(moduleCode, grade)
activate modules

modules --> calculator
deactivate modules

end

end

calculator --> calculator
deactivate calculator

end

@enduml