@startuml
'https://plantuml.com/class-diagram

class Timetable
class SubCommand
class DeleteSubCommand
class ViewSubCommand
class UpdateSubCommand
class AddSubCommand
class Lesson
class Tutorial
class Lecture
class Lab
class TimetableStorage


SubCommand ^-- DeleteSubCommand
SubCommand ^-- ViewSubCommand
SubCommand ^-- AddSubCommand
SubCommand ^-- UpdateSubCommand

Lesson ^-- Lecture
Lesson ^-- Tutorial
Lesson ^-- Lab

AddSubCommand --> "*" Lesson
DeleteSubCommand --> "*" Lesson
UpdateSubCommand --> "*" Lesson
Timetable --> "1" TimetableStorage
Timetable --> "*" Lesson
Timetable --> "1" UpdateSubCommand
Timetable --> "1" ViewSubCommand
Timetable --> "1" DeleteSubCommand
Timetable --> "1" AddSubCommand

TimetableStorage --> "*" Lesson

class Timetable {
+ lessonStorage : ArrayList<Lesson>
+ timetableStorage : TimetableStorage
- addSubCommand : AddSubCommand
- deleteSubCommand : DeleteSubCommand
- updateSubCommand : UpdateSubCommand
- viewSubCommand : ViewSubCommand
+ executeAdd(parsedArguments : String[]) : void
+ executeUpdate(parsedArguments : String[]) : void
+ executeDelete(parsedArguments : String[]) : void
+ executeView(parsedArguments : String[]) : void
}

class TimetableStorage {
- lessonStorage : Lesson
+ writeToFile() : void
+ createFilePath(filePath:String) : void
+ clearFile() : void
}

class AddSubCommand {
}

class DeleteSubCommand {
}

class ViewSubCommand {
}

class UpdateSubCommand {
}



@enduml